config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  get 'contact' => 'contact#index' 

  get 'goals' => 'goals#index'

  get 'progress' => 'progress#index'

  get 'about' => 'about#index'

  get 'skills' => 'skills#index'

  get 'cv' => 'cv#index'

  root 'home#index'

  resources :projects

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/project.rb
class Project < ActiveRecord::Base
	mount_uploader :image, ImageUploader
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
  end
end

app/controllers/cv_controller.rb
class CvController < ApplicationController
  def index
  end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @project = Project.all
  end
end

app/controllers/progress_controller.rb
class ProgressController < ApplicationController
  def index
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)

    if @project.save
      redirect_to @project
    else
      render 'new'
    end
  end

  def update
    @project = Project.find(params[:id])

    if @project.update(project_params)
      redirect_to @project
    else
      render 'edit'
    end
  end

  def edit
    @project = Project.find(params[:id])
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    redirect_to projects_path
  end

  def show
    @project = Project.find(params[:id])
  end

  def index
    @project = Project.all
  end

  private

  def project_params
    params.require(:project).permit(:title, :image, :time, :minor, :work, :result)
  end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  def index
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/cv_helper.rb
module CvHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/progress_helper.rb
module ProgressHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/views/about/index.html.erb
<h1>About#index</h1>
<p>Find me in app/views/about/index.html.erb</p>

app/views/contact/index.html.erb
<h1>Contact#index</h1>
<p>Find me in app/views/contact/index.html.erb</p>

app/views/cv/index.html.erb
<h1>Cv#index</h1>
<p>Find me in app/views/cv/index.html.erb</p>

app/views/goals/index.html.erb
<h1>Goals#index</h1>
<p>Find me in app/views/goals/index.html.erb</p>

app/views/home/index.html.erb
        <div class="section">
            <div class="container">
                <div id='portfolio'></div>
                    <div class="row">
                        <div class="col-md-12">
                            <h1 class="text-center">Portfolio</h1>
                        </div>
                    </div>
                    <div class="row">
                        <% @project.each do |p| %>
                            <div class="col-md-4">
                                <a><%= image_tag p.image.url(:thumb).to_s =%></a>
                                <h3><%= p.title %></h3>
                                <p><%= p.work %>&nbsp;</p>
                            </div>
                        <% end %>
                    </div>
                </div>
            </div>
        </div>

app/views/progress/index.html.erb
<h1>Progress#index</h1>
<p>Find me in app/views/progress/index.html.erb</p>

app/views/projects/_form.html.erb
    <%= form_for @project, multiple: true do |f| %>
      <p>
        <%= f.label :title %><br>
        <%= f.text_field :title %>
      </p>

      <p>
        <%= f.label :image %><br>
        <%= f.file_field :image %>
      </p>
     
      <p>
        <%= f.label :time %><br>
        <%= f.text_area :time %>
      </p>

      <p>
        <%= f.label :minor %><br>
        <%= f.text_area :minor %>
      </p>

      <p>
        <%= f.label :work %><br>
        <%= f.text_area :work %>
      </p>

      <p>
        <%= f.label :result %><br>
        <%= f.text_area :result %>
      </p>
     
      <p>
        <%= f.submit %>
      </p>
    <% end %>

app/views/projects/edit.html.erb
<div class="container">
  <div class="margin_top">
    <div class="padding">
      <h1> Pas huidig project aan </h1>

      <%= render 'form' %>

      <%= link_to 'Back', projects_path %>
    </div>
  </div>
</div>

app/views/projects/index.html.erb
<div class="section">
  <div class="container">
    <div class="padding">  

      <table>
        <tr>
          <th>Titel</th>
          <th>Afbeelding</th>
          <th>Periode</th>
          <th>Minor</th>
          <th>Opdracht</th>
          <th>Opgeleverd</th>
        </tr>

        <% @project.each do |p| %>
          <tr>
            <td><%= p.title %></td>
            <td><%= image_tag p.image.url(:thumb).to_s %></td>
            <td><%= p.time %></td>
            <td><%= p.minor %></td>
            <td><%= p.work %></td>
            <td><%= p.result %></td>
            <td><%= link_to 'Show', project_path(p) %></td>
            <td><%= link_to 'Edit', edit_project_path(p) %></td>
            <td><%= link_to 'Destroy', project_path(p),
                method: :delete,
                data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </table>
      <%= link_to 'Nieuw project', new_project_path %>
    </div>
  </div>
</div>

app/views/projects/new.html.erb
<div class="container">
  <div class="margin_top">
    <div class="padding">
      <h1> Nieuw project </h1>

      <%= render 'form' %>
      <%= link_to 'Back', projects_path %>
    </div>
  </div>
</div>

app/views/projects/show.html.erb
<div class="section">
  <div class="container">
    <div class="padding">


      <table>
        <tr>
          <th>Titel</th>
          <th>Afbeelding</th>
          <th>Periode</th>
          <th>Minor</th>
          <th>Opdracht</th>
          <th>Opgeleverd</th>
        </tr>

        
        <tr>
          <td><%= @project.title %></td>
          <td><%= image_tag @project.image.url(:thumb).to_s %></td>
          <td><%= @project.time %></td>
          <td><%= @project.minor %></td>
          <td><%= @project.work %></td>
          <td><%= @project.result %></td>
          
        </tr>
      </table>
      <%= link_to 'Back', projects_path %>
    </div>
  </div>
</div>

app/views/skills/index.html.erb
<h1>Skills#index</h1>
<p>Find me in app/views/skills/index.html.erb</p>